language: python

python:
- 3.6

install:
- pip install pipenv
- pipenv install --dev
- pipenv install --skip-lock codecov

before_script:
- cp contrib/env-sample .env

script:
- pipenv run flake8 .
- pipenv run pytest . --cov

after_success:
- pipenv run codecov
